name: bootmate
base: core24
version: '1.1.0'
summary: Manage autostart entries
description: |
  Boot Mate provides a simple and intuitive interface to manage your
  system's autostart entries. You can view all autostart applications,
  edit their properties, add startup parameters, or remove them entirely.

  Perfect for managing which applications start automatically when you
  log in to your GNOME session.

grade: stable
confinement: strict

platforms:
  amd64:

apps:
  bootmate:
    command: usr/local/bin/bootmate
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - home
      - dot-config-autostart
      - system-autostart-read
      - desktop-applications-read
    environment:
      XDG_DATA_DIRS: $SNAP/usr/share:$SNAP/usr/local/share:$XDG_DATA_DIRS
      GTK_USE_PORTAL: "1"
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

plugs:
  dot-config-autostart:
    interface: personal-files
    write:
      - $HOME/.config/autostart
    read:
      - $HOME/.config/autostart

  system-autostart-read:
    interface: system-files
    read:
      - /etc/xdg/autostart
      - /usr/share/gnome/autostart

  desktop-applications-read:
    interface: system-files
    read:
      - /usr/share/applications
      - /var/lib/snapd/desktop/applications

parts:
  bootmate:
    plugin: nil
    source: .
    build-packages:
      - curl
      - gcc
      - meson
      - ninja-build
      - pkg-config
      - libgtk-4-dev
      - libadwaita-1-dev
      - libglib2.0-dev
      - libglib2.0-bin
      - gettext
      - desktop-file-utils
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - libglib2.0-0
      - libglib2.0-bin
      - librsvg2-common
      - gsettings-desktop-schemas
    override-build: |
      set -eu

      # Install Rust stable via rustup
      export CARGO_HOME=$CRAFT_PART_BUILD/cargo
      export RUSTUP_HOME=$CRAFT_PART_BUILD/rustup
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal --no-modify-path
      export PATH="$CARGO_HOME/bin:$PATH"

      # Verify Rust installation
      echo "Rust version:"
      rustc --version
      cargo --version

      # Build with meson
      cd $CRAFT_PART_SRC
      meson setup $CRAFT_PART_BUILD --prefix=/usr/local -Dprofile=release
      ninja -C $CRAFT_PART_BUILD
      DESTDIR=$CRAFT_PART_INSTALL ninja -C $CRAFT_PART_BUILD install

      # Cleanup Rust to save space
      rm -rf $CARGO_HOME $RUSTUP_HOME
